let jsonBMW = [
    {id:0, 
        name: 'BMW E71', 
        img: 'images/bmwe71.jpg',
        img1:'images/bmwe71I-01.jpg',
        img2:'images/bmwe71I-02.jpg',
        img3:'images/bmwe71I-03.jpg',
        img4:'images/bmwe711.jpg',
        imgMOBILE: 'images/1.jpg',
        price: '452340 $', 
        description: 'Em 2008, surgiu nas ruas um carro que desafiava classificações: Seria um cupê? Um SUV? Não se trata de  nenhum dos dois, na verdade, embora combinasse as melhores qualidades das duas classes de veículos. É um carro para os individualistas, que valorizam o desempenho sobre todos os aspectos: Dotado de motores de 6 e 8 cilindros, o BMW X6 dispõe de muita potência, perfeitamente distribuída através do Dynamic Performance Control. O DPC, juntamente com a tração inteligente xDrive nas quatro rodas, aumenta a precisão ao dirigir, a estabilidade direcional e também a tração, uma vez que o torque da tração pode agora ser continuamente distribuído individualmente a cada roda.', 
        fabrication: '2008 – 2014', 
        motors:'3.0 – 4.4 litros (173 – 300 kW, 235 – 408 hp), 6 e 8 cilindros', 
        large: '4,876 – 4,877 mm/1,983 mm/1,684 – 1,690 mm', 
        resum: 'É um carro para os individualistas, que valorizam o desempenho sobre todos os aspectos!'
    },
    {id:1, 
        name: 'BMW E84', 
        img: 'images/bmwe841.jpg', 
        img1: 'images/bmwe84I-01.jpg',
        img2: 'images/bmwe84I-02.jpg',
        img3: 'images/bmwe84I-03.jpg',
        img4: 'images/bmwe84I-04.jpg',
        price: '520000 $', 
        description: 'Sua robusta versatilidade posiciona este veículo em uma outra categoria - a calibração de sua mecânica, voltada para o desempenho esportivo, constitui uma garantia de dinâmica e agilidade, sob todas as condições. E com a tração BMW xDrive inteligente nas quatro rodas, tanto a tração como a dinâmica ao dirigir atingem níveis empolgantes, pois a potência de tração é continuamente distribuída para as rodas dianteiras e para o eixo traseiro. Isto assegura o seu prazer ao dirigir, em todos os momentos. O design atraente exibe sua aparência poderosa e esportiva. Ao mesmo tempo, o interior de alta qualidade é realçado a partir dos acabamentos interiores que harmonizam tons de cores, dotados de detalhes em aço inoxidável.', 
        fabrication: '2009 – 2015', 
        motors:'2,0 - 3,0 litros (85 - 225 kW, 116 - 306 cv), 4 e 6 cilindros', 
        large: '4.454 mm / 1.798 mm /1.545 mm', 
        resum: 'Quando de seu lançamento em 2009, o BMW X1 rapidamente se tornou o SUV compacto líder no segmento premium.'
    },
    {id:2, 
        name: 'BMW F15', 
        img: 'images/bmwf15.jpg',
        img1: 'images/bmwf15I-01.jpg',
        img2: 'images/bmwf15I-02.jpg',
        img3: 'images/bmwf15I-03.jpg',
        img4: 'images/bmwf15I-04.jpg',    
        price: '299350 $', 
        description: 'O sofisticado sistema de entrada de ar na dianteira, dotado de uma abertura atrás das rodas dianteiras, reduz a turbulência de ar por sobre as linhas que contornam as rodas dianteiras. Isso não apenas reduz o arrasto, mas também confere um toque de carro esportivo ao BMW X5. As proporções harmoniosas irradiam sofisticação, supremacia e agilidade. O interior possui elegância a partir da iluminação ambiente e do uso de materiais luxuosamente trabalhados e de alta qualidade, tais como o couro com costura dupla. O controlador de toque iDrive, agora reformulado, faz com que controlar os extensos sistemas de assistência ao motorista seja um verdadeiro prazer. Estes incluem o controle automático da velocidade de cruzeiro, incluindo um assistente para  engarrafamentos, bem como um refletor de LED capaz de iluminar pessoas e animais à noite, destacando-os no escuro, o qual integra o sistema Night Vision', 
        fabrication: '2013 – 2018', 
        motors:'2.0 – 4.4 litros (160 – 330 kW, 218 – 450 hp), 4-, 6-, e  8 cilindros', 
        large: '4,880 – 4,886 mm/1,938 – 1,985 mm/1,717 – 1,762 mm', 
        resum: 'As melhorias aerodinâmicas na terceira geração deste SUV de sucesso imediatamente despertam a nossa  atenção.'
    },
    {id:3, 
        name: 'BMW F39', 
        img: 'images/bmwf39.jpg',
        img1: 'images/bmwf39I-01.jpg',
        img2: 'images/bmwf39I-02.jpg',
        img3: 'images/bmwf39I-03.jpg',
        img4: 'images/bmwf39I-04.jpg',  
        price: '215050 $', 
        description: 'Os recortes sobre as rodas, projetados segundo ângulos quase retos, bem como as linhas da carroceria e as soleiras laterais, juntamente com a linha plana do teto, destacam-no como um extraordinário veículo, de disposição extrovertida. A grade curva da BMW se expande para a parte inferior, e as entradas de ar se integram em harmonia com a parte frontal, sinalizando uma autoconfiança sem igual. Os motores turbo modernos, juntamente com a transmissão Steptronic, garantem vigorosa impulsão sob todas as condições. Dotado da tração opcional BMW xDrive nas quatro rodas, o SUV cupê também se sente em casa longe dos ambientes urbanos. A dinâmica ao dirigir, típica da BMW, garante o prazer de dirigir sobre qualquer terreno. Os logotipos da BMW na coluna traseira do veículo são reminiscentes de lendários modelos da BMW, tais como o 2000 CS e o 3.0 CSL.', 
        fabrication: '2018 – today', 
        motors:'1.5 – 2.0 litros (100 – 170 kW, 136 – 231 hp), 3 e 4 cilindros', 
        large: '4,360 mm/1,824 mm/1,512 – 1,526 mm', 
        resum: 'Apresentado pela primeira vez em 2016 enquanto carro-conceito baseado no X1, o design expressivo deste  veículo e a genialidade de sua tecnologia se mostraram inspiradoras.'
    },
    {id:4, 
        name: 'BMW G02', 
        img: 'images/bmwg02.jpg',
        img1: 'images/bmwg02I-1.jpg',
        img2: 'images/bmwg02I-2.jpg',
        img3: 'images/bmwg02I-3.jpg',
        img4: 'images/bmwg02I-4.jpg', 
        price: '472950 $', 
        description: 'Os contornos robustos por sobre as rodas com larga banda de rodagem, aliadas à linha do teto, semelhante ao de um cupê, enfatizam as características típicas do modelo X: potência, supremacia e esportividade. As estreitas luzes de LED traseiras alongam visualmente a traseira do carro, assim como a linha ascendente sobre os para-lamas traseiros. A frente é dominada pela grade curva da BMW com suas duas partes, equipada com faróis de LED estreitos, que conferem ao SUV cupê uma aparência esportiva e dinâmica. O sistema padrão de tração inteligente BMW xDrive nas quatro rodas permite um incomparável dinamismo ao dirigir, juntamente com a transmissão automática de 8 velocidades, a qual também se encontra disponível para todos os modelos BMW X4. Internamente, o veículo agora inclui telas sensíveis ao toque de maior tamanho, controle por meio de gestos e modernos sistemas para assistência ao motorista.', 
        fabrication: '2018 até hoje', 
        motors:'2.0 – 3.0 litros (135 – 210 kW, 184 – 286 hp), 4 e 6 cilindros', 
        large: '4,733 – 4,758 mm/1,918 – 1,938 mm/1,618 – 1,621 mm', 
        resum: 'A elegância esportiva do BMW X4 torna-se ainda mais evidente nesta sua segunda geração.'
    },
    {id:5, 
        name: 'BMW G06', 
        img: 'images/bmwg06.jpg',
        img1: 'images/bmwg06I-01.jpg',
        img2: 'images/bmwg06I-02.jpg',
        img3: 'images/bmwg06I-03.jpg',
        img4: 'images/bmwg06I-04.jpg', 
        price: '399950 $', 
        description: 'Os faróis se tornaram bastante estreitos e abrangentes, tanto à frente como atrás. Eles são responsáveis pela aparência extrovertida do veículo, assim como as grandes entradas de ar nas laterais e também sob a grade curva. Dotados de iluminação própria com a luz laser opcional nos faróis, eles asseguram que a individualidade deste SUV cupê seja sempre reconhecível, mesmo no escuro. Os motores, sistemas de assistência ao motorista, bem como a tração xDrive nas quatro rodas, permitem uma experiência dinâmica ao dirigir sem precedentes.O luxuoso equipamento inclui, opcionalmente, suportes com temperatura controlada para bebidas quentes ou frias e ainda o sistema de som surround Bowers & Wilkins Diamond, contendo 20 alto-falantes. Ao dirigir o BMW X6, você não só atinge seu destino com rapidez e segurança, mas também com conforto.', 
        fabrication: '2019 até hoje', 
        motors:'2.0 – 3.0 litros (195 – 250 kW, 265 – 340 hp), 4 e 6 cilindros', 
        large: '4,935 – 4,948 mm/2,004 – 2,019 mm/1,693 – 1,697 mm', 
        resum: 'As proporções vigorosas, bem como o expressivo design, constituem as marcas registradas do BMW X6 2019 de terceira geração.'
    }
];

//Funções:
function algo() {
    console.log('algo');
}